### ISSUE TITLE
Nifi settings for 1.14.0 changed and cannot start with current operator configuration

### ISSUE THREAD

**Issue by maltesander** [stackabletech/nifi-operator#82]
When implementing up and downgrades (From 1.13.2 -> 1.14.0) i got an error with NiFi.

```
2021-09-16 20:55:20,146 ERROR [main] org.apache.nifi.NiFi Failure to launch NiFi due to java.lang.IllegalArgumentException: There was an issue decrypting protected properties
java.lang.IllegalArgumentException: There was an issue decrypting protected properties
	at org.apache.nifi.NiFi.initializeProperties(NiFi.java:346)
	at org.apache.nifi.NiFi.convertArgumentsToValidatedNiFiProperties(NiFi.java:314)
	at org.apache.nifi.NiFi.convertArgumentsToValidatedNiFiProperties(NiFi.java:310)
	at org.apache.nifi.NiFi.main(NiFi.java:302)
Caused by: org.apache.nifi.properties.SensitivePropertyProtectionException: Sensitive Properties Key [nifi.sensitive.props.key] not found: See Admin Guide section [Updating the Sensitive Properties Key]
	at org.apache.nifi.properties.NiFiPropertiesLoader.getDefaultProperties(NiFiPropertiesLoader.java:220)
	at org.apache.nifi.properties.NiFiPropertiesLoader.get(NiFiPropertiesLoader.java:209)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.nifi.NiFi.initializeProperties(NiFi.java:341)
	... 3 common frames omitted
```
@Jimvin mentioned that they need encryption out of the box. 

Needs investigation.

**Comment by lfrancke** [comment]
Just a heads-up: NiFi 1.15 has been released. As far as I'm concerned the latest version is the only version we need to support at the moment.

**Comment by fhennig** [comment]
I found the problem. It is only a single property, for which - since 1.14 - no default value is provided anymore and an explicit value needs to be given. The property is the encryption key for sensitive properties in flows. If a user would like to migrate from the 1.13 default key to an explicit key, a script needs to be run: https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#updating-the-sensitive-properties-key

If there are no sensitive properties to migrate, the new version can simply be used.

I added a hardcoded key. The key should be configurable, but making nifi secure needs more than that, and that's a seperate issue.

**Comment by fhennig** [comment]
Update: 
- We'll get rid of 1.13 entirely and look at it again if we need it.
- The sensitive props key should be loaded from a secret
